### ISSUE TITLE
Youtube Embedded Video Support?

### ISSUE THREAD

**Issue by Enijar** [fritz-c/react-image-lightbox#17]
First off, great work! I like what you're doing with the project 👍 

Any plans to offer support for embedded video or will this just be a lightbox for images?

**Comment by fritz-c** [comment]
Hm, that's a tough one. I could offer options to render arbitrary content in the lightbox, but then things like zoom and such wouldn't make as much sense (or work). I realize the demand for mixed content in a lightbox, but I think this project is better as a purpose-fit tool, rather than an all-in one solution.
The main obstacle on the code side is that size judgements, preloading and transitions are all based on the pretense that you'll be using images (identifiable by a unique src string). Allowing embedded videos or other content would mean a nasty hack, or a rewrite of about a third of the code.

**Comment by georg199041** [comment]
It's a shame lightbox doesn't support pdfs, zoom for pdfs is needed. Long pdfs can be as a single slide and scroll down, not left/right .

**Comment by vfonic** [comment]
+1 providing option to render arbitrary content would be great!
