### ISSUE TITLE
First image into <iframe> get error "Uncaught DOMException: Blocked a frame with origin..."

### ISSUE THREAD

**Issue by mihrich** [fritz-c/react-image-lightbox#46]
Hello!
The plugin works well. Thanks!
But. If it is put to another website into <iframe> tag i have a error for first image as mainSrc.
But if you click back or forward the next picture works.

Message in console:
"Uncaught DOMException: Blocked a frame with origin "https://mysitename.com" from accessing a cross-origin frame."

Place error supposedly is on 242 line of code
The version plugin is 3.4.1

**Comment by fritz-c** [comment]
Thank you for using the component and giving me the tip on this bug. It's fixed now and available in 3.4.2

The problem was that for some of the event handlers, it's best to have them assigned on the topmost iframe/window so `mouseup`s that occur outside of the browser window are still called. In the case of cross-origin embedding, though, it's not really possible to fiddle with the event handlers of another site, so it was throwing an error. I just added an additional check for the cross-origin case before adding the event handlers.

**Comment by mihrich** [comment]
It works, thanks!!! :)
